---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userdatareporting
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: cosmosdbservice
          image: pdecontainerregistry.azurecr.io/cosmosdbservice:Latest
          ports:
            - containerPort: 9004

 kind: Service 
 apiVersion: v1 
 metadata: 
   name: cosmosdbservice-svc
 spec: 
   selector: 
     app: web 
   ports: 
   - protocol: TCP 
     port: 9004
     targetPort: 9004 
   type: LoadBalancer
